### ISSUE TITLE
Isometric preview

### ISSUE THREAD

**Issue by thomasrudin** [BuckarooBanzay/mtinfo#1]
https://codepen.io/Mythical/pen/xGVMEJ

**Comment by BobFred7** [comment]
I tried replacing the `background: ` statements in CSS with `background-image: ` statements.

But this results in the images being tiled and rotated differently from how they should be in an isometric node preview (at least the front was rotated wrong, not sure about the others).

I was able to easily remove the tiling (with `background-repeat: no-repeat; background-size: cover;`). I'm working on fixing the rotation.
![image](https://user-images.githubusercontent.com/57379622/74781948-89352e00-5270-11ea-9a7d-ef9c33514a76.png)

**Comment by BobFred7** [comment]
I fixed the rotation of the front texture
https://gist.github.com/BobFred7/fcc9bd2d45bc6dbab760a93bb0c2de1f
![image](https://user-images.githubusercontent.com/57379622/74795670-8d734280-5294-11ea-805d-2b9adb537575.png)

**Comment by thomasrudin** [comment]
Nice! Thanks for the pure-css solution, i never got around to test the link in the first comment, i just put it for future reference...

**Comment by BuckarooBanzay** [comment]
incorporated, thanks :+1:
