### ISSUE TITLE
Textures aren't copied correctly

### ISSUE THREAD

**Issue by BobFred7** [BuckarooBanzay/mtinfo#2]
I tried to run `mtinfo` on a singleplayer server as a mod with `minetest_game`
I found `mtinfo`'s output directory and the `textures` subdirectory
It had many .png files in it, but when I tried to view some of them, all the image viewers/editors I tried said that it was an invalid/corrupted file
I opened one of these files in a text editor and turned on viewing all characters
They were mostly blank

**Comment by thomasrudin** [comment]
>  They were mostly blank

So they were all truncated, zero in size?
If so i need to add some proper logging, it currently just ignores missing/not found files...

Can you describe how you started the server? With the UI or on a command-line?

**Comment by BobFred7** [comment]
> So they were all truncated, zero in size?

Not exactly: they had the characters "PNG" and a couple other characters, but no actual data for the full image

> Can you describe how you started the server? With the UI or on a command-line?

I ran a singleplayer minetest world from the minetest GUI

After opening the world and then exiting, I looked through the files.

**Comment by BuckarooBanzay** [comment]
should be fixed with 3674a9344e6be6266cecdd4eecc6383e55ceda4b
