### ISSUE TITLE
Webapp doesn't work consistently between browsers

### ISSUE THREAD

**Issue by BobFred7** [BuckarooBanzay/mtinfo#3]
After running `mtinfo` on my singleplayer world, I opened index.html from `mtinfo`'s output directory.
It displays a borderless table with itemstrings and a column what appears to be copies of the icon for an invalid image when viewed in MS Edge, which I suspect is what was intended.
When I view it in Google Chrome, it's blank white. No table or itemstrings.
I accessed it from the same file on the same computer.

**Comment by thomasrudin** [comment]
> I opened index.html from mtinfo's output directory.

The app currently needs a webserver to run due to the requests it sends, i'm surprised this worked in edge... :astonished: 

I see if i can actually fix that, it would make the thing a bit more portable... :+1:

**Comment by BobFred7** [comment]
> The app currently needs a webserver to run due to the requests it sends,

I didn't even know about that part; didn't read the instructions :laughing:

**Comment by thomasrudin** [comment]
> I didn't even know about that part; didn't read the instructions laughing

"instructions" ... yeah, good one... :stuck_out_tongue:

**Comment by thomasrudin** [comment]
With the latest commit it should now be possible to open the app just with double-clicking the `index.html` file, even across browsers...

**Also**: added basic instructions in the readme...

The app still looks the same though, no changes in the UI department...

**Comment by BuckarooBanzay** [comment]
changed to a new view-framework (vue) and updated the bootstrap files, _should_ work across browsers now, if not: feel free to reopen
