### ISSUE TITLE
Bug in copying node descriptions (extra weird characters)

### ISSUE THREAD

**Issue by BobFred7** [BuckarooBanzay/mtinfo#6]
I looked at the `node.js` (I just realized how unintentionally funny that filename is :stuck_out_tongue: ) output file from `mtinfo`, and saw that all the node's `description` attributes have an extra `"\u001b(T@modname)"` (`modname` is replaced with the actual modname of each node) at the start and a `"\u001bE"` at the end. This does not occur with any other node attributes. I have not checked if this happens with items, recipes, etc, so I'm not sure if this is also a problem with those.

**Comment by BuckarooBanzay** [comment]
fixed with translation step in 4691175a30790f15611b9215e367cb164320a5f9
